### PR TITLE
:hammer: Extracting address using Geocoder api

### PR DESCRIPTION
**Pull request by victorgvieira**
NOTE: Pointed this to master as there doesn't seem to be a develop branch anywhere

Relevant Issues :
#1

What Changed and Why? :
Changing the strategy to extract the address name using Geocoder Api.
I'm not sure, but i think that some functions that uses PlacePicker may not work due to [depreciation](https://developers.google.com/android/reference/com/google/android/gms/location/places/ui/PlacePicker)

Please, test the changes and see if it fit yours requirements

### CODE REVIEW

**Comment by mmuhamadamirzaidi** [comment]
Will check tomorrow morning and also, it is great if you can provide the screenshot @victorgvieira. Thanks in advance.

**Comment by victorgvieira** [comment]
The final result
image
image

**Comment by victorgvieira** [comment]
the **null** at the end it's from the the Volley request, maybe you'll need to get a newer api_key
`{"destination_addresses":[],"error_message":"The provided API key is expired.","origin_addresses":[],"rows":[],"status":"REQUEST_DENIED"}`

**Comment by mmuhamadamirzaidi** [comment]
Hi @victorgvieira . I have updated the API key, it works. Yeah, the deprecation issues, maybe I will open another issue for this. You may contribute if you will :). Thanks.

**Pull request merged**
